# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 1

# Personal info
name: Roberto De Filippo
title: Neuroscience PhD
# email: roberto.defilippo@outlook.com

# Social links
twitter_username: RobertoDeF_
github_username:  RobertoDF
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: jameswgrant
linkedin_username: https://www.linkedin.com/in/roberto-de-filippo-883a1b54/
# pinterest_username:
# youtube_username:
# googleplus_username:
orcid_username: 0000-0002-4085-9114
# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: |
  Hi, my name is Roberto De Filippo, I am a neuroscientist interested in neuromodulation and sensory perception. 
  Currently my main focus is <mark>serotonin</mark>, in vivo recording with high-density probes (Neuropixel) and Machine Learning in the cntext of neural decoding.
  I have experience working with:
  <mark>Python</mark>,
  <mark>Tensorflow</mark>
  <mark>Matlab</mark> and
  <mark>git</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: When I'm Not Programming
# more_content: |


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme

# sass:
#   style: compressed
