# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 1

# Personal info
name: Roberto De Filippo
title: Neuroscience PhD
# email: roberto.defilippo@outlook.com

# Social links
twitter_username: RobertoDeF_
github_username:  RobertoDF
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: jameswgrant
linkedin_username: https://www.linkedin.com/in/roberto-de-filippo-883a1b54/
# pinterest_username:
# youtube_username:
# googleplus_username:
orcid_username: 0000-0002-4085-9114
# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: |
  Hi, my name is Roberto De Filippo, I am a neuroscientist interested in neuromodulation and sensory perception. 
  Currently my main focus is <mark>serotonin</mark>, in vivo recording with high-density probes (Neuropixel) and Machine Learning in the context of neural decoding.
  I have experience working with:
  <mark>Python</mark>,
  <mark>Tensorflow</mark>
  <mark>Matlab</mark> and
  <mark>git</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Publications
more_content: |
  **Somatostatin interneurons activated by 5-HT2A receptor suppress slow oscillations in medial entorhinal cortex.** Elife. 2021 Mar 31;10:e66960. doi: 10.7554/eLife.66960. PMID: 33789079; PMCID: PMC8016478.\
  de Filippo R<sup>*</sup>, Rost BR, Stumpf A, Cooper C, Tukker JJ, Harms C, Beed P, Schmitz D<sup>*</sup>.\
  <sup>*</sup> = corresponding authors


  **Layer 3 Pyramidal Cells in the Medial Entorhinal Cortex Orchestrate Up-Down States and Entrain the Deep Layers Differentially.** Cell Rep. 2020 Dec 8;33(10):108470. doi: 10.1016/j.celrep.2020.108470. PMID: 33296656.\
  Beed P<sup>*</sup>, de Filippo R<sup>*</sup>, Holman C<sup>*</sup>, Johenning FW, Leibold C, Caputi A, Monyer H, Schmitz D.\
  <sup>*</sup> = equal contribution

  **Pin1 Modulates the Synaptic Content of NMDA Receptors via Prolyl-Isomerization of PSD-95.** J Neurosci. 2016 May 18;36(20):5437-47. doi: 10.1523/JNEUROSCI.3124-15.2016. PMID: 27194325; PMCID: PMC6601765.\
  Antonelli R, De Filippo R, Middei S, Stancheva S, Pastore B, Ammassari-Teule M, Barberis A, Cherubini E, Zacchi P. 


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme

# sass:
#   style: compressed
